name: Logging Secret Leak

on:
  workflow_dispatch:

jobs:
  secret_leak_plaintext:
    runs-on: ubuntu-latest
    steps:
      - name: Print SUPER_DUPER_SECRET
        run: echo "The SUPER_DUPER_SECRET is $SUPER_DUPER_SECRET"
        env:
          SUPER_DUPER_SECRET: ${{ secrets.SUPER_DUPER_SECRET }}

  secret_leak_base64:
    runs-on: ubuntu-latest
    steps:
      - name: Print SUPER_DUPER_SECRET
        run: |
          echo "SUPER_DUPER_SECRET (base64):"
          echo -n "$SUPER_DUPER_SECRET" | base64
        env:
          SUPER_DUPER_SECRET: ${{ secrets.SUPER_DUPER_SECRET }}
  
  secret_leak_caesar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Print SUPER_DUPER_SECRET
        run: |
          echo "SUPER_DUPER_SECRET (base64):"
          python3 $GITHUB_WORKSPACE/src/cipher/cipher.py encode $SUPER_DUPER_SECRET
        env:
          SUPER_DUPER_SECRET: ${{ secrets.SUPER_DUPER_SECRET }}

  secret_leak_plaintext_cimon:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0

      - name: Print SUPER_DUPER_SECRET
        run: echo "The SUPER_DUPER_SECRET is $SUPER_DUPER_SECRET"
        env:
          SUPER_DUPER_SECRET: ${{ secrets.SUPER_DUPER_SECRET }}

  secret_leak_base64_cimon:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0

      - name: Print SUPER_DUPER_SECRET
        run: |
          echo "SUPER_DUPER_SECRET (base64):"
          echo -n "$SUPER_DUPER_SECRET" | base64
        env:
          SUPER_DUPER_SECRET: ${{ secrets.SUPER_DUPER_SECRET }}
  
  secret_leak_caesar_cimon:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Print SUPER_DUPER_SECRET
        run: |
          echo "SUPER_DUPER_SECRET (base64):"
          python3 $GITHUB_WORKSPACE/src/cipher/cipher.py encode $SUPER_DUPER_SECRET
        env:
          SUPER_DUPER_SECRET: ${{ secrets.SUPER_DUPER_SECRET }}
