name: Simple Command Injection

on: 
  issues:
    types: opened

jobs:
  simple_command_injection:
    runs-on: ubuntu-latest
    steps:
      - name: Open door for PWN Attack
        run: |
          echo "${{ github.event.issue.title }}"

  simple_command_injection_cimon:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0

      - name: Open door for PWN Attack
        run: |
          echo "${{ github.event.issue.title }}"